[project]
name = "stacks-daily-raffle"
description = "A decentralized daily lottery on Stacks blockchain"
authors = []
telemetry = false
cache_dir = "./.cache"

[contracts.daily-raffle]
path = "contracts/daily-raffle.clar"
clarity_version = 2
epoch = 2.5

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }